# Site settings
title: RTB House Technical Blog
image: img/home-bg.jpg
logo: img/fav1.png
email: piotr.jaczewski@rtbhouse.com
description: "Projects we’re currently working on, thoughts on things we tried, research results etc…"
baseurl: ""
author: "Piotr Jaczewski"
url: "https://techblog.rtbhouse.com"
twitter_username: rtbhouse
github_username: RTBHOUSE
facebook_username: RTBHouse
gaid: UA-98436697-1
disqus_site_id: ""
copyright_name: RTB HOUSE

# Plugins
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
safe: false # safe need to be off for local preview
lsi: false
permalink: pretty
paginate: 10
exclude: ["sass","node_modules","Gruntfile.js","package.json","README.md","vendor"]
keep_files: []
