title: RTB House Tech Blog
email: rtbhouse@rtbhouse.com
description: > #
  RTB House Technical Blog
baseurl: ""
url: "http://techblog.rtbhouse.com" #
twitter_username: rtbhouse
github_username:  rtbhouse

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
