title: RTB House Tech Blog
email: your-email@domain.com
description: > #
  RTB House technical blog
baseurl: "/techblog" # the subpath of your site, e.g. /blog
url: "https://rtbhouse.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rtbhouse
github_username:  rtbhouse

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
